server: server_main.c server.h board_handling.h board_handling.c server_communication.c server_communication.h common.h 
	gcc -W -g server_main.c server_communication.c board_handling.c  -o server -pthread 
